name: test.yml

on:
  pull_request:
    branches: [ main ]

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install



      - name: Run Linter
        run: pnpm run lint


      - name: Run Tests with Coverage
        run: pnpm run test -- --coverage

