name: test.yml

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Prettify code
        run: pnpm run prettify

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: prettify"
          file_pattern: '**/src/**/*.{ts,tsx,js,jsx,json,scss,css}'

      - name: Run Linter
        run: pnpm run lint

      - name: Run types check
        run: pnpm run type-check

      - name: Run Tests
        run: pnpm run test
